### ISSUE TITLE
sixuanyi.slx找不到roblocks

### ISSUE THREAD

**Issue by yanlei2017** [wuhaoran996/openRobotics#2]
另外，找不到Quadrotor文件

**Comment by L3Y1Q2** [comment]
http://petercorke.com/wordpress/toolboxes/robotics-toolbox

**Comment by L3Y1Q2** [comment]
> 另外，找不到Quadrotor文件
1、MATLAB版本；2、需要下载这个工具箱，楼主的仿真是在这个的基础上修改的
http://petercorke.com/wordpress/toolboxes/robotics-toolbox
