### ISSUE TITLE
Plan and Execute Collision-Free Trajectories无法运算出结果

### ISSUE THREAD

**Issue by Hoesen6** [wuhaoran996/openRobotics#7]
大佬我是从B站看的你的视频，想问一下为啥我的matlab无法计算机械臂出避障轨迹规划的结果啊，一直在计算，在主函数的timestep的for循环中，timestep都上万了

**Comment by songyaochen** [comment]
详细讲讲，啥情况？

在 2021-12-22 21:24:08，Hoesen6 ***@***.***> 写道：


大佬我是从B站看的你的视频，想问一下为啥我的matlab无法计算机械臂出避障轨迹规划的结果啊，一直在计算，在主函数的timestep的for循环中，timestep都上万了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hoesen6** [comment]
> 详细讲讲，啥情况？ 在 2021-12-22 21:24:08，Hoesen6 ***@***.***> 写道： 大佬我是从B站看的你的视频，想问一下为啥我的matlab无法计算机械臂出避障轨迹规划的结果啊，一直在计算，在主函数的timestep的for循环中，timestep都上万了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Hoesen6** [comment]
> 详细讲讲，啥情况？ 在 2021-12-22 21:24:08，Hoesen6 ***@***.***> 写道： 大佬我是从B站看的你的视频，想问一下为啥我的matlab无法计算机械臂出避障轨迹规划的结果啊，一直在计算，在主函数的timestep的for循环中，timestep都上万了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

我也不太清楚该怎么描述，Plan and Execute Collision-Free Trajectories这个文件包下是关于MATLAB 7自由度机械臂 避障+路径规划的代码，我跑了这个代码，无论如何没法出结果，我的理解是在有的障碍的前提下路径规划不好求解，因为需要判断的次数太多了。但是看B站上就能看到可以跑出结果。B站视频：https://www.bilibili.com/video/BV1J7411i7Kd from=search&seid=3911199713874726776&spm_id_from=333.337.0.0
[Plan and Execute Collision-Free Trajectories.zip](https://github.com/wuhaoran996/openRobotics/files/7780406/Plan.and.Execute.Collision-Free.Trajectories.zip)
